---
title: "STATS 506 HW 2"
author: "Anuraag Ramesh"
date: "October 27, 2022"
output:
  pdf_document:
    toc: yes
    df_print: paged
  html_document:
    toc: yes
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo =TRUE, comment=NA, out_width=100, warning = FALSE)
library(data.table)
library(dplyr)
library(tidycensus)
library(tidyverse)
library(RMySQL)
```

## Q1. 


## Q2. 

```{r}
df_func <- function(n1, n2){
  headers = read.table('Data/2020_Business_Academic_QCQ.txt', sep = ',', nrows = 1,
                       encoding = 'UTF-8')
  df = read.table('Data/2020_Business_Academic_QCQ.txt', sep = ',', skip = n1, nrows = n2 - n1, fileEncoding="latin1")
  colnames(df) = headers
  df = df %>% select('State', 'County Code', 
                'Employee Size (5) - Location', 
                'Sales Volume (9) - Location', 
                'Census Tract')
  colnames(df) = gsub('-', '', colnames(df))
  colnames(df) = gsub('\\(\\d\\)', '', colnames(df))
  colnames(df) = gsub(' ', '', colnames(df))
  colnames(df) = tolower(colnames(df))
  df <- df[complete.cases(df), ]
  
  return(df)
}

```

## Q3. 

```{r}
df = data.frame()
for (i in seq(1, 300001, by = 20000)){
  if(i == 1){
    n1 = i
  }
  else{
    n2 = i
    df1 = df_func(n1, n2)
    n1 = n2
    df = rbind(df, df1)
  }
}
```

```{r}
agg = df %>% group_by(censustract) %>%
  summarise(employeesize = sum(employeesizelocation),
            salesvolume = sum(salesvolumelocation))
df1 = data.frame(agg)

df1
```


## Q4. 

Table creation in SQL:

CREATE TABLE df1 (
	censustract VARCHAR(255),
	employeesize INT,
	salesvolume INT
)

```{r}
host_name = 'localhost'
port_no = 3306
db_name = 'HW3db'
u_id = 'root'

pwd = Sys.getenv('sqlpwd')

conn = RMySQL::dbConnect(RMySQL::MySQL(), host = host_name, port = port_no, user = u_id,
                         password = pwd, dbname = db_name)

RMySQL::dbWriteTable(conn, name = 'df1', df1, append = TRUE, row.names = FALSE)
```

## Q5. 

```{r}
res = dbGetQuery(conn, 'SELECT censustract, salesvolume FROM df1 ORDER BY salesvolume DESC LIMIT 10')
res
```

## Q6. 


```{r}

```

## Q7. 

```{r}

```

## Q8. 

```{r}

```

## Q9. 

```{r}

```

## Q10. 

```{r}

```

## Q11. 

```{r}

```

## Q12. 

```{r}

```

## Q13. 

```{r}

```
